"""The window icon, a 64 px PNG, generated by tooling; tk loads it as a
PhotoImage so the taskbar and title bar stop showing Python's feather."""
ICON_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAAABt0RVh0"
    "U29mdHdhcmUAVGsgVG9vbGtpdCB2OC42LjE1Q7KaAwAAAUFJREFUeJzt27ENwjAQheFMgJDYgoKO"
    "WWgoaFmMmdgGlAYZ5MS+8zn4vTukKyn+LxYkkT1Nis/xdH6NOJoWVexufxhyzFFGD64FcRfeBMEW"
    "L0Jgja9GYI5PEdzGLyKwL/0cwBeCp/jsKgiAAHAMUBP/fFwWp8f3NkWovfqMCCIARgQxABuCCoAJ"
    "QQ3AgtAEwIDQDICOYAKAjGAGgIpgCoCIYA6AhtAFAAmhGwAKQlcABAQRwPV2p0OoApjDf4cFoQiQ"
    "i2dC2BRgRIRVgLV4FoRYAfEbEP8CcR8Qd4LxLBBPg/E+wGW8OQBavCkAYrwZAGq8CQByfDMAenwT"
    "AEO8GoAlXgXAFC8GYIv/ANTsFKOOd79PMAACILbLu1sFrk+NFM8MMSO4Pjnm+uygKJ4JQh2eQ0jn"
    "32Gl4HSa4iUoI4ym5Q16nRcXMkOoygAAAABJRU5ErkJggg=="
)
